language: node_js

node_js:
  - "8"
  - "10"

# sudo: required

# services:
#  - docker

env:
  - CXX=g++-4.8 JOBS=1 PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1

cache:
  yarn: true

addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
install: yarn

script:
  - node scripts/l10n.js generate
  - yarn lint:scss
  - COVERAGE=true yarn test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash scripts/pr_deploy.sh
 # - bash kubernetes/travis/deploy.sh
