[build]
  command = "node scripts/l10n.js generate && ember build -prod"
[build.environment]
  NODE_VERSION = "12"
[context.production]
  [context.production.environment]
    API_HOST = "https://open-event-api-dev.herokuapp.com"
